config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', 
                                  password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :lists
  resources :lists do
    resources :expenses 
  end
  get 'statistics/index'
  post 'statistics/index'
  get 'reminders' => 'expenses#reminders'
  get 'welcome/index'
  root 'welcome#index'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	before_filter :authorize_signed_in

	def reminders
	  	@user_reminders_show = current_user.expenses.where("status = 'not-paid' AND (reminder_status = 'pending' OR reminder_status = 'remindered') AND date <= '#{DateTime.now}'").order('date DESC')
	end


	def index
		redirect_to lists_path
	end

	def show
		@list = current_user.lists.find(params[:list_id])
		@expense = @list.expenses.find(params[:id])
		if @expense.reminder_status == 'pending'
			@expense.reminder_status = 'remindered'
			@expense.save
		end
	end

	def new
		@list = current_user.lists.find(params[:list_id])
	end

	def create
	  @user = User.find(current_user.id)
	  @expense = @user.lists.find(params[:list_id]).expenses.create(expense_params)
	 
	  @expense.save
	  redirect_to @expense.list
	end

	def edit
		@list = List.find(params[:list_id])
		@expense = @list.expenses.find(params[:id])
	end

	def update
		@user = User.find(current_user.id)
		@list = @user.lists.find(params[:list_id])
	  	@expense = @list.expenses.find(params[:id])

	  	@expense_dup = nil
	  	if @expense.status == 'not-paid'
	  		@expense_dup = @expense.dup
	  	else
			@expense.reminder_status = 'not-remindered'
	  	end
	 
		if @expense.update(expense_params)
			if @expense_dup && @expense.repeatable? && @expense.status == 'paid'
				@expense_dup.date = @expense.date + @expense.repeat_interval
				@expense_dup.reminder_status = 'not-remindered'
				@list.expenses << @expense_dup
				@list.save
			end
	  		redirect_to @expense.list
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(current_user.id)
		@list = @user.lists.find(params[:list_id])
	  	@expense = @list.expenses.find(params[:id])
	  	@expense.destroy
	  	@list.save
	  	redirect_to @list
	end
	 
private
	def expense_params
	    params.require(:expense).permit(:title, :amount, :date, :description, :status, :repeatable, :repeat_interval)
	end

	def authorize_signed_in
		return unless !user_signed_in?
		redirect_to root_path, alert: 'Musisz być zalogowany!'
	end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/edit.html.erb
<h1>Nowa pozycja</h1>

<%= form_for :expense, url: list_expense_path(:id => @expense.id, :list_id => @list.id), method: :patch do |f| %>
  <p>
    <%= f.label :Nazwa %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :Kwota %><br>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :status, 'Status' %><br>
    <%= f.radio_button :status, 'paid', :checked => true %> 
    <%= f.label :status_paid, 'Opłacone' %>
    <%= f.radio_button :status, 'not-paid' %>
    <%= f.label :status_not_paid, 'Planowane' %>
  </p>
  <p>
    <%= f.label :Data %><br>
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :repeatable, 'Powtarzalny' %><br>
    <%= f.radio_button :repeatable, false, :checked => true %> 
    <%= f.label :repeatable_no, 'Nie' %>
    <%= f.radio_button :repeatable, true %>
    <%= f.label :repeatable_yes, 'Tak' %>
  </p>
  <p>
    <%= f.label :repeat_interval, 'Powtarzany co' %><br>
    <%= f.select :repeat_interval, Expense::REPEAT_INTERVALS.map{ |c| [c[:text], c[:val]] } %> 
  </p>
  <p>
    <%= f.label :Opis %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :Zapisz %>
  </p>
<% end %>

<%= link_to '<-Back', list_path(:id => @list.id) %>

app/views/expenses/index.html.erb
<h1>Listing spendings</h1>

<%= link_to '<--BACK', controller: 'welcome' %>


<%= link_to 'Nowa lista', new_list_path %>
 
<table>
  <tr>
    <th>Nazwa</th>
  </tr>
 
  <% @lists.each do |list| %>
    <tr>
      <td><%= link_to list.name, {:controller => "lists", :action => "show", :id => list.id } %></td>
    </tr>
  <% end %>
</table>

app/views/expenses/new.html.erb
<h1>Nowa pozycja</h1>

<%= form_for :expense, url: list_expenses_path do |f| %>
  <p>
    <%= f.label :Nazwa %><br>
    <%= f.text_field :title, :list => "names_list" %>
  </p>
  <datalist id="names_list">
    <option value="Zakupy">
    <option value="Prąd">
    <option value="Gaz">
    <option value="Kebab">
    <option value="Jedzenie">
    <option value="Piwo">
    <option value="Zapiekanka">
    <option value="Kosmetyki">
    <option value="Chleb">
    <option value="Ksero">
    <option value="Drozdżówka">
  </datalist>
  <p>
    <%= f.label :Kwota %><br>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.label :status, 'Status' %><br>
    <%= f.radio_button :status, 'paid', :checked => true %> 
    <%= f.label :status_paid, 'Opłacone' %>
    <%= f.radio_button :status, 'not-paid' %>
    <%= f.label :status_not_paid, 'Planowane' %>
  </p>
  <p>
    <%= f.label :Data %><br>
    <%= f.date_select :date %>
  </p>
  <p>
    <%= f.label :repeatable, 'Powtarzalny' %><br>
    <%= f.radio_button :repeatable, false, :checked => true %> 
    <%= f.label :repeatable_no, 'Nie' %>
    <%= f.radio_button :repeatable, true %>
    <%= f.label :repeatable_yes, 'Tak' %>
  </p>
  <p>
    <%= f.label :repeat_interval, 'Powtarzany co' %><br>
    <%= f.select :repeat_interval, Expense::REPEAT_INTERVALS.map{ |c| [c[:text], c[:val]] } %> 
  </p>
  <p>
    <%= f.label :Opis %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit :Dodaj %>
  </p>
<% end %>

<%= link_to '<-Back', list_path(:id => @list.id) %>

app/views/expenses/reminders.html.erb
<hr>
<h2>Przypomnienia</h2>
<% @user_reminders_show.each do |reminder| %>
	<div class="col-md-12 <%= (reminder.reminder_status == 'pending' ? 'bg-colored' : '') %>">		
		<div class="col-md-6"><h3><strong><%= reminder.title %></strong> (<%= reminder.list.name %>)</h3></div>
		<div class="col-md-3"><%= link_to 'Pokaż', list_expense_path(:id => reminder.id, :list_id => reminder.list_id) %></div>
		<div class="col-md-3"><%= link_to 'Edytuj', edit_list_expense_path(:id => reminder.id, :list_id => reminder.list_id) %></div>
	</div>
<% end %>


<hr>

app/views/expenses/show.html.erb
<%= link_to '< Wstecz', list_path(:id => @list.id), :class => "button" %>

	<div class="col-md-12">		
		<div class="col-md-6"><h3><strong><%= @expense.title %></strong> (<%= @list.name %>)</h3></div>	
		<div class="col-md-3">
			<div class="col-md-4"><%= link_to 'Edytuj', edit_list_expense_path(:id => @expense.id, :list_id => @list.id), :class => 'button' %></div>
			<div class="col-md-4"><%= link_to 'Usuń', list_expense_path(:id => @expense.id, :list_id => @list.id), method: :delete, :class => 'button', :data=>{:confirm => 'Czy na pewno chczesz usuąć?'}  %></div>
		</div>
	</div>
	<div class="col-md-12">		
		<div class="col-md-3">Kwota</div>
		<div class="col-md-3">Status</div>
		<div class="col-md-3">Data</div>
	</div>
	<div class="col-md-12">
		<div class="col-md-3"><%= @expense.amount %></div>
		<div class="col-md-3"><%= @expense.status %></div>
		<div class="col-md-3">
	        <% if @expense.date.present? %>
	        <%= @expense.date.strftime("%Y-%m-%d") %>
	        <% end %>
    	</div>
	</div>
	<div class="col-md-12">
		<div class="col-md-9">Opis</div>
		<div class="col-md-9"><%= @expense.description %></div>
	</div>



<hr>