config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', 
                                  password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :lists
  resources :lists do
    resources :expenses 
  end
  get 'statistics/index'
  post 'statistics/index'
  get 'reminders' => 'expenses#reminders'
  get 'welcome/index'
  root 'welcome#index'

end

app/views/layouts/application.html - Kopia.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menedżer wydatków</title>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap-theme.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  	body {
  		background-image: url("/images/body-bg.jpg");
  	}
  	.navbar {
  		background-image: url("/images/navbar-bg.png");
  		height: 25px;
  		position: fixed;
  		width: 100%;
  		left: 0px;
  		top: 0px;
  	}
  	.body {
  		position: relative;
  	}
  	.content {
  		background-color: #fafafa;
  		min-height: 80vh;
  		height: 100%;
  		padding: 12px 12px 12px 12px;
  		border-radius: 20px;
  		margin-right: 15%;
  		margin-left: 15%;
  		margin-top: 7%;
  		margin-bottom: 5%;
  	}
  </style>
</head>
<body>

	<div class="body">
		<div class="header">
			<div class="navbar">
				<% if user_signed_in? %>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete %></div>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Profil', edit_user_registration_path %></div>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Statystyki', statistics_index_path %></div>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Wydatki', lists_path %></div>
				<% else %>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Rejestracja', new_user_registration_path %></div>
					<div class="nav-item col-md-1 pull-right" ><%= link_to 'Zaloguj', new_user_session_path %></div>
				<% end %>
					<div class="nav-item col-md-1 pull-left" ><%= link_to 'Home', root_path %></div>
			</div>
		</div>

		<div class="content">
			<div class="infos">
				<p class="notice"><%= flash[:notice]  %></p>
				<p class="alert"><%= flash[:alert] %></p>
			</div>

			<%= yield %>

		</div>

		<div class="footer">
		</div>
	</div>

</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap-theme.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Menedżer wydatków</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0,user-scalable = no">
    <meta name="googlebot" content="index, follow" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="/style/general.css">
    <link rel="stylesheet" href="/style/framework.css">
    <link rel="stylesheet" href="/style/site.css">
    <link rel="stylesheet" href="/style//prettyPhoto.css" type="text/css" media="screen"
        title="prettyPhoto main stylesheet" charset="utf-8" />
    <script src="/js/modernizr-2.0.6.min.js" type="text/javascript"></script>
</head>
<body>
    <div class="mother">
        <header class="mast-head stack-fixed clearfix">
      
      <article class="logo">
        <a href="index.html"></a>
      </article>
      
      <nav class="main-nav">
      
        <ul>
          <li class="first"><%= link_to 'Główna', root_path, :class => (current_page?(root_path) ? "selected" : "") %></li>
        <% if user_signed_in? %>
          <li class=""><%= link_to 'Listy wydatków', lists_path, :class => (current_page?(lists_path) ? "selected" : "")  %></li>
          <li class=""><%= link_to 'Statystyki', statistics_index_path, :class => (current_page?(statistics_index_path) ? "selected" : "")  %></li>
          <li class=""><i class="icon-user"></i><%= link_to 'Profil', edit_user_registration_path, :class => (current_page?(edit_user_registration_path) ? "selected" : "")  %></li>
          <li class=""><i class="icon-book"></i><%= link_to "(#{@user_reminders.count})", reminders_path, :class => (current_page?(reminders_path) ? "selected" : "")  %></li>
          <li class="last"><%= link_to 'Wyloguj', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li class=""><%= link_to 'Rejestracja', new_user_registration_path, :class => (current_page?(new_user_registration_path) ? "selected" : "")  %></li>
          <li class="last"><%= link_to 'Zaloguj', new_user_session_path, :class => (current_page?(new_user_session_path) ? "selected" : "")  %></li>
        <% end %>
        </ul>
        
      </nav><!-- end .main-nav -->
      
    </header>
<article class="main" role="main">
<div class="home-hero">
  <div class="top-mast">

    <div class="content">
      <div class="infos">
        <p class="notice"><%= flash[:notice]  %></p>
        <p class="alert"><%= flash[:alert] %></p>
      </div>

      <%= yield %>

    </div>   
     
  </div>
</div>


</article>

        <section class="stack-fixed entry-text footer clearfix">
  
  
  <ul class="slat-8 first">
      
    <li>
          <p>
            Zarządzaj swoimi wydatkami razem z nami! Twórz listy, dodawaj pozycje oraz obserwuj statystyki. Żadnych zbędnych funkcji!
          </p>
            
        </li>
    
  </ul>  
  
  <ul class="slat-4 last">
    <li><i class="icon-envelope"></i> <a href="mailto:contact@expenses_manager.com">contact@expenses_manager.com</a></li>
  </ul>
  
</section>
    </div>
    <script src="/js/jquery.min.js" type="text/javascript"></script>
    <script defer src="/js/accessories-min.js" type="text/javascript"></script>
    <script defer src="/js/site.js" type="text/javascript"></script>
    <script src="/js/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $("a[rel^='prettyPhoto']").prettyPhoto();
        });
    
    </script>
    <!--[if lt IE 7 ]>
  <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
  <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>